#!/bin/bash
set -e
if echo dGVzdA== | base64 -D >/dev/null 2>&1; then B64FLAG="-D"; else B64FLAG="-d"; fi
mkdir -p pages
echo 'Writing pages/_app.js...'
base64 $B64FLAG << 'B64_GA_1' > pages/_app.js
aW1wb3J0IFNjcmlwdCBmcm9tICduZXh0L3NjcmlwdCcKaW1wb3J0ICcuLi9zdHlsZXMvZ2xvYmFscy5jc3MnCgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBBcHAoeyBDb21wb25lbnQsIHBhZ2VQcm9wcyB9KSB7CiAgcmV0dXJuICgKICAgIDw+CiAgICAgIDxTY3JpcHQKICAgICAgICBzdHJhdGVneT0iYWZ0ZXJJbnRlcmFjdGl2ZSIKICAgICAgICBzcmM9Imh0dHBzOi8vd3d3Lmdvb2dsZXRhZ21hbmFnZXIuY29tL2d0YWcvanM/aWQ9Ry0yRVZaRzZEMVpIIgogICAgICAvPgogICAgICA8U2NyaXB0IGlkPSJnb29nbGUtYW5hbHl0aWNzIiBzdHJhdGVneT0iYWZ0ZXJJbnRlcmFjdGl2ZSI+CiAgICAgICAge2AKICAgICAgICAgIHdpbmRvdy5kYXRhTGF5ZXIgPSB3aW5kb3cuZGF0YUxheWVyIHx8IFtdOwogICAgICAgICAgZnVuY3Rpb24gZ3RhZygpe2RhdGFMYXllci5wdXNoKGFyZ3VtZW50cyk7fQogICAgICAgICAgZ3RhZygnanMnLCBuZXcgRGF0ZSgpKTsKICAgICAgICAgIGd0YWcoJ2NvbmZpZycsICdHLTJFVlpHNkQxWkgnKTsKICAgICAgICBgfQogICAgICA8L1NjcmlwdD4KICAgICAgPENvbXBvbmVudCB7Li4ucGFnZVByb3BzfSAvPgogICAgPC8+CiAgKQp9Cg==
B64_GA_1
echo 'Google Analytics installed.'
